[package]
name = "secd-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
secd-machine = { git = "https://github.com/lemolatoon/SECDMachine.git", version = "0.1.0" }

