name: Cloudflare Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
     
      - name: install deps
        run: pnpm install
      
      - name: build wasm
        run: pnpm build-wasm
      
      - name: build
        run: pnpm build
     
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=just-beta-transform
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}